# Dependencies
markdown: kramdown

kramdown:
   input: GFM
   syntax_highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude: [vendor]

# Permalinks
permalink: /blog/:title/

# Site
title: 'Anver Bogatov'
description: 'Бесконечность - не предел.'
url: http://www.anverbogatov.com
logo: /img/logo.png
timezone: SAMT

twitter:
  username: anver_bogatov

img_url: /img

# Author
author:
  name: 'Anver Bogatov'
  twitter: anver_bogatov

# Setup
paginate: 4
excerpt_separator: <!--excerpt-->

# Data
links:
  github: 'https://github.com/anverbogatov/anverbogatov.github.io'
  issue: 'https://github.com/anverbogatov/anverbogatov.github.io/issues/new'
  pull: 'https://github.com/anverbogatov/anverbogatov.github.io/compare'

social_links:
  twitter: 'https://twitter.com/anver_bogatov'
  github: 'https://github.com/anverbogatov'
  linkedin: 'https://www.linkedin.com/in/anver-bogatov-64b32661/'
  vk: 'https://vk.com/anverbogatov'
